### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by interrogator** [interrogator/buzzword#15]
We should probably have a nice admin dashboard to allow admins to manage users.

https://flask-admin.readthedocs.io/en/latest/ / https://github.com/flask-admin/flask-admin

https://www.codementor.io/chirilovadrian360/flask-dashboard-argon-learn-flask-by-coding-an-admin-panel-w03jaks12

**Comment by l0rb** [comment]
it's not gonna be flask, but it will be nice

**Comment by interrogator** [comment]
Yes note above links are old because app switched to django. django luckily makes this even easier...

**Comment by l0rb** [comment]
This has been implemented with pull #26 . Admin site is available at `/admin` and only needs a superuser to be created via `manage.py createsuperuser`

**Comment by interrogator** [comment]
This is nice. Todo now is to have an admin section for #41
